mod:boothttp: create config dir in install step
To avoid this weird dep cycle:
  Error: Could not apply complete catalog: Found 1 dependency cycle:
  (Archive[/var/www/disk/calibre9/netboot.tar.gz]
   => Class[Boothttp::Install]
   => Class[Boothttp::Config]
   => Boothttp::Printconfig[calibre9]
   => File[/var/www/disk/calibre9]
   => Archive[/var/www/disk/calibre9/netboot.tar.gz])

I cannot figure out why File requires the Archive, it is probably
something weird in the archive module. Anyway, ensuring the directories
in the install step avoids the cycle.